### ISSUE TITLE
Wrong account data

### ISSUE THREAD

**Issue by salessandrelli** [commercionetwork/sacco.cs#10]
https://github.com/commercionetwork/sacco.cs/blob/3bdf6ea9b680b725c8291b8ec818565827b7d4a1/sacco/Code/utils/AccountDataRetrieval.cs#L87
The raw account_number property in JSON seems to be numeric so the safe type casting set the parsed account number to null. This leads to wrong account data. Is it intended?

**Comment by ErichUdet** [comment]
This was a problem created by the new version of network. Now it is fixed.
