### ISSUE TITLE
Cosmos 0.38 support

### ISSUE THREAD

**Issue by Valentina-92** [commercionetwork/sacco.cs#7]
@ErichUdet 

Currently **Sacco** intercepts LCD responses that are based on the old Cosmos SDK; it needs to correctly intercept responses from the new SDK version 0.38 while maintaining compatibility with version 0.37. 

In the new version some response 'json' change and it is necessary to manage cases. In case of error, for example, the 'raw_log' can be a string or an object (map); note that only in error responses the code is present. I attach some sample answers.

[Archivio.zip](https://github.com/commercionetwork/sacco.kt/files/4416021/Archivio.zip)

The addresses to test are:
- 'https://lcd-testnet.commercio.network' (old)
- 'https://lcd-internal.commercio.network' (new)

The versions developed in **Dart** and **Kotlin** of **Sacco** have already been updated.
It can be useful to understand which classes have to be updated.

cc: @marcotradenet

**Comment by ErichUdet** [comment]
Fixed and working now.
